[package]
name = "flutter-wizard"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive", "color"] }
thiserror = "2"
inquire = "0.9"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
